// Code generated by "stringer -type=ProfilerMode"; DO NOT EDIT.

package profiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Block-0]
	_ = x[Cpu-1]
	_ = x[Goroutine-2]
	_ = x[Mem-3]
	_ = x[Mutex-4]
	_ = x[ThreadCreate-5]
	_ = x[Trace-6]
}

const _ProfilerMode_name = "BlockCpuGoroutineMemMutexThreadCreateTrace"

var _ProfilerMode_index = [...]uint8{0, 5, 8, 17, 20, 25, 37, 42}

func (i ProfilerMode) String() string {
	if i < 0 || i >= ProfilerMode(len(_ProfilerMode_index)-1) {
		return "ProfilerMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProfilerMode_name[_ProfilerMode_index[i]:_ProfilerMode_index[i+1]]
}
